### ISSUE TITLE
Checkbox

### ISSUE THREAD

**Issue by schwantuschke** [dgmid/nextcloud-notes-mac-client#10]
The markdown checkbox like 

- [ ] Text

Code: `- [ ] Text`
looks strange with a dot before the checkbox and have no function in preview mode.

**Comment by dgmid** [comment]
This is something I have on my TODO list so hopefully I will get around to implementing it sometime.
It would be nice if the Nextcloud Notes app actually supported this too.

**Comment by sunjam** [comment]
[See this merged PR adding checkbox support](https://github.com/nextcloud/notes/pull/303) to the Notes web app.

**Comment by dgmid** [comment]
Checkboxes are already implemented and will be available in the next release (1.3.6)

![checkboxes-edit](https://user-images.githubusercontent.com/1267580/68548156-18b58000-03ea-11ea-8367-1d7a0e7e1e54.png)
![checkboxes-preview](https://user-images.githubusercontent.com/1267580/68548159-1b17da00-03ea-11ea-94f1-9b658aab49e7.png)

**Comment by dgmid** [comment]
[v1.3.6](https://github.com/dgmid/nextcloud-notes-mac-client/releases/tag/v1.3.6) which includes checkbox lists has been released
