### ISSUE TITLE
Access notes from Local Storage

### ISSUE THREAD

**Issue by sunjam** [dgmid/nextcloud-notes-mac-client#11]
Hi, I was curious about accessing notes from local storage within this app, since these same directories could also be synchronized via the Nextcloud Desktop app.

**Comment by dgmid** [comment]
Hi @sunjam 
This app doesn't work with local copies. It uses the [nextcloud notes API](https://github.com/nextcloud/notes/wiki/Notes-0.2) to obtain the  content of the notes online. Then when you save it saves via the API directly back to your nextcloud instance.

If you happen to also sync the contents of the Notes folder to your Hard drive using the Nextcloud sync app, all that would happen is that on saving a note it would be saved via the notes API directly to Nextcloud - then the Nextcloud app would update the copy on your Hard drive.
