### ISSUE TITLE
New language: German

### ISSUE THREAD

**Issue by lucanello** [dgmid/nextcloud-notes-mac-client#12]
Hey,

I really like your app and would like to help translate it to German.
Is there any possibility?

Thanks
Luca

**Comment by dgmid** [comment]
@lucanello A german translation would be really great!
The files to translate are located in:

`app-source/i18n/`

currently there are the original english strings and an italian translation.
Just duplicate the **'en'** folder and rename it **'de'** then translate the individual files inside.

Or if you prefer I can provide a text file of all strings to translate.
