### ISSUE TITLE
Feature requests

### ISSUE THREAD

**Issue by Dietbrand** [dgmid/nextcloud-notes-mac-client#13]
Hello, Ciao

Awesome app so far. I've been looking for a replacement to qOwnNotes for a while. I have a few feature requests:

1. Would it be possible to toggle the display of the preview in the title of the note? This could make navigating notes a bit easier and more compact.
2. Another toggle I'd really like is to always be in edit mode.
3. Autosaving. When I make a new note, type something in it then switch to a new note, the things I typed were not saved.

Sadly, I don't know much about Javascript/Node yet but I'd love to contribute. Tips/pointers would be really helpful.

**Comment by dgmid** [comment]
Hi @Dietbrand ,

Thanks for the input. Can you clarify what you mean by:
> toggle the display of the preview in the title of the note

Regarding 2. I could add a preference to the app to make new note open in edit mode - this way users have a choice.

Regarding 3. This is on my list of things to do, although I won't make it autosave as notes can get accidentally overwritten that way (personally I have autosaving in the background). I would make the save dialog open - that way there is a choice.

**Comment by Dietbrand** [comment]
Hello again,

Thanks for getting back to me. I've attached a screenshot. The text of the note is visible in thie note while I would only need the title.
![Screenshot 2020-03-06 at 09 09 36](https://user-images.githubusercontent.com/5815621/76064652-630ad000-5f8a-11ea-9337-b3c32562789e.png).
Regarding 2. Yes :) More options are always nice. 
Regarding 3. I can live with that.

Kind regards

Dietbrand

**Comment by dgmid** [comment]
@Dietbrand  - ok, I understand what you're saying about the title / description now.
It's not something I will be changing as it goes against the general premise of the app.

Basically, Nexcloud can be made to sync with the default Mac Calendar, Reminders & Contacts app, but NOT with the default Mac Notes app. The idea of this app is to emulate the Mac Notes app - but syncing with Nextcloud Notes. Obviously there are some diferences as Nextcloud Notes uses Markdown whereas the Mac Notes app uses Rich Text. But at least the aim is to keep it familiar and as similar as possible:
<img width="1167" alt="NCN-Mac_Notes" src="https://user-images.githubusercontent.com/1267580/76124279-a3a23200-5ffa-11ea-8f98-b82dbaa77436.png">

**Comment by sisyphosloughs** [comment]
Hi,

first of all thank you for the nice and straight forward app! It is easy, intuitive and looks nice!

As a user basd in Germany I only miss two things: 

- Spellchecking for German.
- Date formated in Geramn.

Would be nice, if localiscation could be based on the MacOS default. Coustomisation is from my point of view not necessary, as your app is very simple -- what I like!

Regards

**Comment by dgmid** [comment]
Hi @sisyphosloughs 
I've added Dates formatted in German to my list.
Spellchecking is a bit more difficult. The app is built using [EasyMDE](https://www.npmjs.com/package/easymde) which at the moment only has spellchecking in EN. That might change - or I might be able to work around it - but at the moment on EN works :(

**Comment by dgmid** [comment]
Hi @sisyphosloughs can you confirm the correct date format for German. Should it be:
2020.03.21
is that correct?

**Comment by sisyphosloughs** [comment]
Hi @dgmid, I have just dowloaded the app from your home page. Date fromat looks for me still the same:
![grafik](https://user-images.githubusercontent.com/11442081/77224158-149d2a00-6b63-11ea-8102-be531dbeabaa.png)

**Comment by dgmid** [comment]
Hi @sisyphosloughs 
I have not made any changes yet. Before I do, can you give me an example of the correct date format.
Should it be like this? -> 2020.03.21

**Comment by sisyphosloughs** [comment]
@dgmid , sorry for that missunderstanding:

For the list:
TT.MM.YYYY, example 20.03.2020

For the title
TT. MMM YYYY, esymple 20. März 2020

I hope that hellps!

**Comment by dgmid** [comment]
Danke, das ist perfekt.

**Comment by dgmid** [comment]
@Dietbrand re:

> Another toggle I'd really like is to always be in edit mode.

in the next release (v.1.4.1), if the app is in edit mode, the app remain in edit mode when you switch between notes and on closing and restarting the app. The same is valid the app is in preview mode.

**Comment by dgmid** [comment]
@sisyphosloughs German date formats will be in the next release (v1.4.1) - however the app does not have a German translation.

**Comment by dgmid** [comment]
@sisyphosloughs 
```
As a user basd in Germany I only miss two things:
Spellchecking for German.
```
[EasyMDE](https://www.npmjs.com/package/easymde) have added multilingual spell checking and Electron have fixed a bug that was stopping me from using v8.x —  so this should be available in the next release

**Comment by stratmaster** [comment]
> @sisyphosloughs German date formats will be in the next release (v1.4.1) - however the app does not have a German translation.

Does that mean, nobody is working on a german translation of the app so far? I'd like to help out and could provide a german translation in the next few days.

**Comment by dgmid** [comment]
OK, this has all worked out really well!
EasyMDE now has multilingual spell checking and @stratmaster has very kindly provided a full German translation.
Both these featured will be be in the next release v1.4.2
