### ISSUE TITLE
Link on webpage wrong

### ISSUE THREAD

**Issue by hechi** [dgmid/nextcloud-notes-mac-client#14]
Hey @dgmid 

the issue is not really regarding your app, which is btw super awesome, it's about your webpage https://www.midwinter-dg.com/mac-apps/nextcloud-notes-client.html
The link to the **Nextcloud Notes App** is going to the **Nextcloud Bookmarks app**

Thx a lot for your time and also making in open source :)
Stay safe

**Comment by dgmid** [comment]
Hi @hechi 
Thanks for taking the time to let me know :)
this is now fixed!
