### ISSUE TITLE
Menu items missarranged for german translation

### ISSUE THREAD

**Issue by stratmaster** [dgmid/nextcloud-notes-mac-client#16]
For the german translation (see PR #15), some menu items are missarranged:

https://github.com/dgmid/nextcloud-notes-mac-client/blob/2e1f39832873c01e59d13fe1f59026f01134dbf4/app-source/js/menu-app.js#L52

https://github.com/dgmid/nextcloud-notes-mac-client/blob/2e1f39832873c01e59d13fe1f59026f01134dbf4/app-source/js/menu-app.js#L67

For both, the variable `${name}`has to be at the beginning of each label.

**Comment by dgmid** [comment]
@stratmaster Thanks for contributing the German translation!
These strings have now been modified
