### ISSUE TITLE
Suggestion for interfering shortcut cmd-H

### ISSUE THREAD

**Issue by stratmaster** [dgmid/nextcloud-notes-mac-client#17]
Shortcut cmd-H is meant for adding a headline _and_ for hiding the app. Changing the shortcut for adding headlines would allow hiding the app, regardless where the current focus within the app is lying on.

**Comment by dgmid** [comment]
Fixed in https://github.com/dgmid/nextcloud-notes-mac-client/commit/80999628eb5f5f3349061d764fc8828c821a98fa
