### ISSUE TITLE
[Feature Request] Split Editor

### ISSUE THREAD

**Issue by stratmaster** [dgmid/nextcloud-notes-mac-client#18]
Having a split view would allow previewing a note while editing it in markdown view. For example like this: https://github.com/notable/notable#split-editor

**Comment by dgmid** [comment]
I decided against a split view as this app was created as a replacement for the default Mac Notes app (which can't sync with Nextcloud).So with that in mind I have kept the interface as close to the original Mac app as possible, ie: 2 sidebars and 1 main view for the notes.

By choosing to toggle between the markdown and the preview, I am following the behaviour of the actual Nextcloud Notes app, which also doesn't use a split view.

<img width="745" alt="nc-notes" src="https://user-images.githubusercontent.com/1267580/80724797-8a04fe80-8b02-11ea-8c65-f56d4420ad10.png">

**Comment by stratmaster** [comment]
Thank you, your decision is understandable against this background.
