### ISSUE TITLE
Menu entry "Show Category Icons" does not seem to work

### ISSUE THREAD

**Issue by stratmaster** [dgmid/nextcloud-notes-mac-client#19]
When activating/deactivating the menu entry "Show Category Icons", this does not have any effect.

**Comment by dgmid** [comment]
this options toggles the category icons in the list sidebar:
**With icons**
<img width="434" alt="icons" src="https://user-images.githubusercontent.com/1267580/80723030-5d4fe780-8b00-11ea-879b-00481460ad24.png">
**Without icons**
<img width="434" alt="no-icons" src="https://user-images.githubusercontent.com/1267580/80723074-6e005d80-8b00-11ea-8c8c-d1f4b69ca149.png">
The icons/category names are only visible if the category selected is: 'All notes', 'Favorites' or 'Uncategorised'.

**Comment by stratmaster** [comment]
Thanks for the explanation, I missed that.
