### ISSUE TITLE
icon layout cut off

### ISSUE THREAD

**Issue by octochamp** [dgmid/nextcloud-notes-mac-client#2]
mac OS 10.13.6, MBP Retina mid-2014

icons at top of notes appear to be cut in half by a glitch in the app layout

<img width="654" alt="Screen Shot 2019-04-16 at 10 26 58" src="https://user-images.githubusercontent.com/49677546/56198394-c8806600-6032-11e9-8e8e-5a2eb1c8e779.png">

**Comment by salsysd** [comment]
Yep I was just gonna open an issue regarding this...

[](https://nxtcloud.me/s/nc-notes-ui-cutoff)

**Comment by dgmid** [comment]
this is now resolved in v.1.0.1
