### ISSUE TITLE
Windows and Linux releases?

### ISSUE THREAD

**Issue by e-alfred** [dgmid/nextcloud-notes-mac-client#20]
Hello,

I forked the app like the bookmark viewer and it works nicely on Linux and Windows with a few small problems like too bright font colours if an element is clicked:

![image](https://user-images.githubusercontent.com/10073629/82793473-3e2f4600-9e71-11ea-9191-b7c99b0db429.png)

![image](https://user-images.githubusercontent.com/10073629/82793514-4be4cb80-9e71-11ea-9a00-bc588599b4a3.png)

**Comment by dgmid** [comment]
Hi @e-alfred 
the main window background in main.js is using `vibrancy: 'under-window'` to make the transparent window effect in macOS.

It seems that appears as white on Linux / Windows?

You will need to either change the window background, or the CSS for the white elements that are not visible.

You will probably also need to set a color for selected items, as I am using the Mac Accent color which won't be available in Win/Linux.
