### ISSUE TITLE
Move focus to Hyperlink field when clicking link button

### ISSUE THREAD

**Issue by reinvented** [dgmid/nextcloud-notes-mac-client#21]
When editing a note, I click the hyperlink button and a dialog slides down titled "Insert a hyperlink," but focus is not on the "Hyperlink" field, so I need to take the additional step of clicking on the field before I can paste or type a URL.

I would be helpful if focus was moved to this field automatically on clicking the hyperlink button.

**Comment by dgmid** [comment]
@reinvented noted: I will make the first field focused in all dialogs.
For now you can just use one extra keypress instead of going for the mouse:
`cmd-k` to add a hyperlink, the `tab` to focus the first field.

**Comment by dgmid** [comment]
@reinvented hyperlink filed is focused in v1.4.4
