### ISSUE TITLE
iOS version

### ISSUE THREAD

**Issue by aniqueta** [dgmid/nextcloud-notes-mac-client#23]
@dgmid Not sure if this is the best place to ask this, apologies if not. Any chance you have plans to develop an iOS version? Not sure how challenging this is, given this appears to be a web app at the core? Sadly, this is outside of my own skill level to contribute. This app is fantastic, and there is no alternatives, so just thought I'd ask. Thanks.

**Comment by dgmid** [comment]
Hi @aniqueta - this should be what you are looking for:
https://apps.apple.com/app/cloudnotes-owncloud-notes/id813973264

**Comment by aniqueta** [comment]
@dgmid Thanks. I had seen that, but it looks quite basic. Your app is significantly more mature with a GUI for markdown formatting and the functionality to embed images. So, I take this means you do not have any interest in porting to iOS? Understand, just wanted to check. Thanks.

**Comment by dgmid** [comment]
I have no means to make an iOS version and no need for it -- i have no iPhone and I'm not paying for an Apple Developer account -- also I know nothing of development for iOS!
It's a shame that app doesn't do images  :(

**Comment by aniqueta** [comment]
Fair enough. Thanks for considering though!
