### ISSUE TITLE
Feature request: mermaid.js

### ISSUE THREAD

**Issue by Brice187** [dgmid/nextcloud-notes-mac-client#24]
If it doesn't require much effort, support for displaying [mermaid.js](https://mermaid-js.github.io/) would be nice

**Comment by dgmid** [comment]
You can easily include a chart just by copying the [markdown formatted url](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZXJEaWFncmFtXG4gICAgICAgICAgVEVTVCB9fC4ufHsgREVMSVZFUlktQUREUkVTUyA6IGhhc1xuICAgICAgICAgIENVU1RPTUVSIHx8LS1veyBPUkRFUiA6IHBsYWNlc1xuICAgICAgICAgIENVU1RPTUVSIHx8LS1veyBJTlZPSUNFIDogXCJsaWFibGUgZm9yXCJcbiAgICAgICAgICBERUxJVkVSWS1BRERSRVNTIHx8LS1veyBPUkRFUiA6IHJlY2VpdmVzXG4gICAgICAgICAgSU5WT0lDRSB8fC0tfHsgT1JERVIgOiBjb3ZlcnNcbiAgICAgICAgICBPUkRFUiB8fC0tfHsgT1JERVItSVRFTSA6IGluY2x1ZGVzXG4gICAgICAgICAgUFJPRFVDVC1DQVRFR09SWSB8fC0tfHsgUFJPRFVDVCA6IGNvbnRhaW5zXG4gICAgICAgICAgUFJPRFVDVCB8fC0tb3sgT1JERVItSVRFTSA6IFwib3JkZXJlZCBpblwiXG4gICAgICAgICAgICAiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ) and including it in your note, like this:

[![](https://mermaid.ink/img/eyJjb2RlIjoiZXJEaWFncmFtXG4gICAgICAgICAgVEVTVCB9fC4ufHsgREVMSVZFUlktQUREUkVTUyA6IGhhc1xuICAgICAgICAgIENVU1RPTUVSIHx8LS1veyBPUkRFUiA6IHBsYWNlc1xuICAgICAgICAgIENVU1RPTUVSIHx8LS1veyBJTlZPSUNFIDogXCJsaWFibGUgZm9yXCJcbiAgICAgICAgICBERUxJVkVSWS1BRERSRVNTIHx8LS1veyBPUkRFUiA6IHJlY2VpdmVzXG4gICAgICAgICAgSU5WT0lDRSB8fC0tfHsgT1JERVIgOiBjb3ZlcnNcbiAgICAgICAgICBPUkRFUiB8fC0tfHsgT1JERVItSVRFTSA6IGluY2x1ZGVzXG4gICAgICAgICAgUFJPRFVDVC1DQVRFR09SWSB8fC0tfHsgUFJPRFVDVCA6IGNvbnRhaW5zXG4gICAgICAgICAgUFJPRFVDVCB8fC0tb3sgT1JERVItSVRFTSA6IFwib3JkZXJlZCBpblwiXG4gICAgICAgICAgICAiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/#/edit/eyJjb2RlIjoiZXJEaWFncmFtXG4gICAgICAgICAgVEVTVCB9fC4ufHsgREVMSVZFUlktQUREUkVTUyA6IGhhc1xuICAgICAgICAgIENVU1RPTUVSIHx8LS1veyBPUkRFUiA6IHBsYWNlc1xuICAgICAgICAgIENVU1RPTUVSIHx8LS1veyBJTlZPSUNFIDogXCJsaWFibGUgZm9yXCJcbiAgICAgICAgICBERUxJVkVSWS1BRERSRVNTIHx8LS1veyBPUkRFUiA6IHJlY2VpdmVzXG4gICAgICAgICAgSU5WT0lDRSB8fC0tfHsgT1JERVIgOiBjb3ZlcnNcbiAgICAgICAgICBPUkRFUiB8fC0tfHsgT1JERVItSVRFTSA6IGluY2x1ZGVzXG4gICAgICAgICAgUFJPRFVDVC1DQVRFR09SWSB8fC0tfHsgUFJPRFVDVCA6IGNvbnRhaW5zXG4gICAgICAgICAgUFJPRFVDVCB8fC0tb3sgT1JERVItSVRFTSA6IFwib3JkZXJlZCBpblwiXG4gICAgICAgICAgICAiLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlfQ)
