### ISSUE TITLE
[Feature] Tags

### ISSUE THREAD

**Issue by chriswep** [dgmid/nextcloud-notes-mac-client#28]
Don't know how complicated this is, however Nextcloud has tags, so there would be a backend available for this.

In the context of notes i would consider tags to be super useful. Implantation suggestion:

- show existing tags as well as a "+" button as hovering buttons/badges at the bottom left (similar to the edit note button)
- wither wenn clicking "+" or CMD+ALT+T a popup opens with auto-suggest input (and existing tags below it for clicking). multiple tags can be entered separated by comma. not existing tags will be created.
- the left sidebar shows a list of used tags at the bottom. i would personally scope this to the selected category (and hide non-used tags)

**Comment by dgmid** [comment]
Nextcloud has tags as you say, but the Notes app for Nextcloud doesn't use them, and has no way to access the using it's API.
As my app communicates to the Notes app using the API, there is no way I can implement this.
