### ISSUE TITLE
Feature Request:  autosave

### ISSUE THREAD

**Issue by ab0oo** [dgmid/nextcloud-notes-mac-client#37]
Had an issue this morning where I lost a pretty good chunk of work.  My security cert expired on my Nextcloud server (technically, it expired on my nginx proxy TO my Nextcloud server, but...).  When I tried to change editing from one note to the other, it gave me several error screens about cert not valid, complained it couldn't save, and went into a cert-fail loop where it kept telling me the cert was invalid, and I would acknowledge it, and the same modal dialog would pop back up.
I put a valid cert on the server, and the dialog went away, but it also took a bunch of unsaved data from the first note with it.
Having an auto-save (i.e. every X minutes) would have
a) notified me that I had a bogus cert earlier
b) let me know when I wasn't in the middle of switching from one note to another, putting me in weird middle ground where data was at risk.

Just something to consider.  Thanks!
John Gorkos

**Comment by ei8fdb** [comment]
An autosave function would be very helpful. I use your Notes client for interviews and sometimes I'm writing for a large period of time, then large periods where I'm not typing and sometimes forget to save.

A "basic" (as in, it doesn't have to be too intelligent/highly configurable) autosave every 30seconds/1/2/5 minutes would be very helpful.

**Comment by dgmid** [comment]
As I wrote in this other thread: https://github.com/dgmid/nextcloud-notes-mac-client/issues/26
Autosave is only going to happen, if EasyMDE allow a custom function to be called in their Autosave function: 
cf. [Ionaru/easy-markdown-editor#42](https://github.com/Ionaru/easy-markdown-editor/issues/42)

I personally have no problem pressing `⌘ S` once in a while.

**Comment by dgmid** [comment]
Closing this tread as there is already an open thread with the same request
