### ISSUE TITLE
“Nextcloud Notes Client.app” cannot be opened because the developer cannot be verified.

### ISSUE THREAD

**Issue by jd1** [dgmid/nextcloud-notes-mac-client#40]
I get this warning when I try to open the application which I downloaded from the website. I know there is a workaround to use the software, but this message may prevent some users from using software. This would be a pity.

**Comment by dgmid** [comment]
The only way to get rid of this notification is to code-sign the app.
Code signing requires an Apple Developer licence which costs (last time I looked) about €80 p.a.
So it's not really going to happen for a free app.
