### ISSUE TITLE
[Feature] Big Sur Design Adaptation

### ISSUE THREAD

**Issue by tricolon** [dgmid/nextcloud-notes-mac-client#41]
The design no longer matches the UI of the current Mac OS version. To make the application more attractive for new users, an adaptation to the Big Sur design should be considered.
The following picture shows the default Notes App in Mac OS Big Sur:

![image](https://user-images.githubusercontent.com/35114966/123162372-d337b080-d470-11eb-8ea0-a2abf71b6487.png)

**Comment by dgmid** [comment]
The next release will have an updated UI

<img width="1167" alt="ncn-ui" src="https://user-images.githubusercontent.com/1267580/123741208-ed76f180-d8a9-11eb-9554-010021cbca95.png">
