### ISSUE TITLE
Apple silicon support

### ISSUE THREAD

**Issue by BJKle** [dgmid/nextcloud-notes-mac-client#45]
Hi,
is it possible to provide an additional apple silicon app or at least an universal app?
This would be great. 
I’m not a developer otherwise I would try to compile one myself. 
Thanks in advance.
B.J.

**Comment by dnisbetjones** [comment]
I would like to +1 this feature request. I would definitely appreciate a native M1 client.

I followed the donate link on this project to support it.

**Comment by BJKle** [comment]
No response after 3 months. Issue closed.

**Comment by mada199122** [comment]
Please native Apple silicon support...
