### ISSUE TITLE
Select Notes with Key

### ISSUE THREAD

**Issue by schwantuschke** [dgmid/nextcloud-notes-mac-client#5]
I find this app and it's a good app for nextcloud notes on mac.
One idea I have: I want select the individual note with arrow keys.

Is it possible to implement this feature?

**Comment by dgmid** [comment]
This should be possible already. You may have to tab into the sidebar first. Then you should be able to use the up and down keys to navigate the notes.

It may be that tabbing has been slightly disrupted after I implemented categories. Ill have to check that.

**Comment by schwantuschke** [comment]
Thank. Yes, please check it. It dosn't work on my computer with the newest version.

**Comment by dgmid** [comment]
this has been fixed and will be available in the next release
