### ISSUE TITLE
during notes loading, edit mode visible

### ISSUE THREAD

**Issue by schwantuschke** [dgmid/nextcloud-notes-mac-client#6]
If i select a another note the app load it and somtime i see the note in edit mode before the formated text is visible. And somtimes the formated text don't load and i see the raw text (like edit mode) but i can't edit. If i use cmd+E for edit i can edit and with next cmd+E i the the formated text.

Do you know this behavior? It's a bug?

**Comment by dgmid** [comment]
Does this happen with all notes, or does it only happen with one particular note?

**Comment by schwantuschke** [comment]
I have 2 note with this problem. I've wrote you a mail with the note and a example video.
In fullsceen this view mode load faster then in window mode.

**Comment by dgmid** [comment]
Do the two notes that have this problem have tables in them, and if so, how many rows / columns do the tables have?

**Comment by schwantuschke** [comment]
The notes don't have tables. Only headlines, text and code blocks.
I just see when I'm waiting the view mode appears after approx. 3 seconds.
I sent you one note and a video by mail at info@midwinter-dg.com. I hope you can comprehend the problem with that.

**Comment by dgmid** [comment]
I haven't received any email -- can you re-send?

**Comment by schwantuschke** [comment]
Ok, I've re-send the mail at info@midwinter-dg.com.

**Comment by dgmid** [comment]
This has been fixed and will be available in the next release.
Thanks for your help!

**Comment by dgmid** [comment]
v1.3.2 is now available.

**Comment by schwantuschke** [comment]
Works fine, great. Thank you :)
