### ISSUE TITLE
Self-signed certificate

### ISSUE THREAD

**Issue by bendschs** [dgmid/nextcloud-notes-mac-client#7]
I am using a self-signed certificate on my nextcloud host and have a strong suspicion that this is what prevents me from logging in via the notes-mac client.

The official Nextcloud client opens a window when I log in where I can add the "Security Exception". Would it be possible to do this in notes-mac-client as well?

Cheers
Bendsch

**Comment by dgmid** [comment]
I think you're correct. A self-signed certificate is not going to work as there is currently no way to trust/approve it.
I would need to implement a trust dialog ( [dialog.showCertificateTrustDialog](https://electronjs.org/docs/api/dialog#dialogshowcertificatetrustdialogbrowserwindow-options-macos-windows) ).

**Comment by bendschs** [comment]
that would be great ... after some research i did not find a single way around it on OS-side.

**Comment by dgmid** [comment]
I set up a test server with a self-signed certificate and got the app to work with it:

First, you need to import the certificate into your Login Keychain in the Keychain Access app (if it's not already installed there).

If the certificate is not in your keychain, you can get it by opening your nextcloud in a web browser and clicking on the lock icon in the address bar. When the dialog open, select 'Show Certificate' and then drag the certificate out of the window.

![certificate-dialog](https://user-images.githubusercontent.com/1267580/66157416-0d6d7880-e624-11e9-95a2-f35024fc4afd.png)

You can then import it into Keychain Access.

Then, click on the certificate in Keychain Access to open it, click on 'Trust' and select 'Always trust' from the first drop-down menu.

<img width="844" alt="keychain-access" src="https://user-images.githubusercontent.com/1267580/66157477-25dd9300-e624-11e9-8e9b-9cfc45931f63.png">

You should then be able to use the app as the certificate will be trusted.

**Comment by bendschs** [comment]
i had added the certificate to my key-chain. i deleted and re-added it but it still does not work for me. i am on 10.14.6.

**Comment by bendschs** [comment]
so ... i guess i have to look for another notes client?

**Comment by dgmid** [comment]
Well, I don't know how to resolve this - or rather I can make it work with a self-signed certificate but the solution is not working for you.

You could try using a Let's Encrypt certificate - that's what I use on my server.

Failing that you could try using [Joplin](https://joplinapp.org) which is an excellent notes app. It syncs with Nextcloud - although I'n not sure if it uses the Nextcloud Notes app.

**Comment by bendschs** [comment]
thank you for the recommendation. i tried Joplin but i (would) prefer your app, becuase oft the simple interface so i am still trying to make it work. in the newest release there is a little log-information about the sign-in process available that i wanted to share:

`[error] loginflow window did not load`

don't know if this helps troubleshooting the certificate problem.

cheers
bendsch
